SELF_EXTRACT_TARGET=self.bin
SELF_EXTRACT_SCRIPT=self.sh
PACKAGE_DATA=package.tgz
PACKAGE_DIR=sourcedir

all: $(SELF_EXTRACT_TARGET)

clean: $(SELF_EXTRACT_TARGET) $(PACKAGE_DATA)
	rm -f $(SELF_EXTRACT_TARGET) $(PACKAGE_DATA)

$(PACKAGE_DATA):
	tar cvfz $@ $(PACKAGE_DIR)

$(SELF_EXTRACT_TARGET): Makefile $(SELF_EXTRACT_SCRIPT) $(PACKAGE_DATA)
	cat $(SELF_EXTRACT_SCRIPT) $(PACKAGE_DATA) > $@
	chmod +x  $@
